config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  devise_for :users
  resources :amenities
  resources :cities
  resources :roles
  resources :cities
  resources :rooms
  resources :my_rooms
  resources :amenity_rooms
  root 'rooms#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
belongs_to :user
belongs_to :city
has_many :bookings
has_many :amenity_rooms
has_many :amenities,through: :amenity_rooms
validates_presence_of :name,:description,:price,:rules,:address	,:images,:city_id,:user_id
mount_uploader :images, CoverUploader
#usage of the callback
before_create :assign_the_role_of_guest_to_host
after_create :assign_the_lat_and_lon_magnitudes
after_create :make_the_default_authorize
 def assign_the_role_of_guest_to_host 
    if !(self.user.role_id == 1)
    binding.pry
    self.user.update_attributes(role_id: Role.second.id)
    binding.pry
    end
 end
 def assign_the_lat_and_lon_magnitudes
     binding.pry
     response=HTTParty.get("https://maps.googleapis.com/maps/api/geocode/json?address=#{self.address}&key=AIzaSyBAmEU8JjAreoouKtDoxZcGvggs0rxa6T8")
     self.update_attributes(latitude:response.parsed_response["results"][0]["geometry"]["location"]["lat"].to_f)
     self.update_attributes(longitude:response.parsed_response["results"][0]["geometry"]["location"]["lng"].to_f)
     binding.pry
 end
 def make_the_default_authorize
      binding.pry
         self.update_attributes(is_authorized: false)    
      binding.pry
 end 	
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource 
  #url:localhost:3000/rooms
  #httpmethod :GET
  #roles and responsibilities :to create a index of the rooms and the attributes that it holds
  #path rooms_path
  def index
      binding.pry
      @rooms=Room.paginate(:page => params[:page], :per_page => 3)
      binding.pry
  end
  #url:localhost:3000/rooms/new
  #path: new_room_path
  #rolesand responsibilities:to give the variable @room for which the attributes can be assigned
  #http method :GET
  def new
    binding.pry
    @room=Room.new
  end
  #http method:post 
  def create
    @room =Room.new(room_params)
    @room.user_id = current_user.id
    
    binding.pry
    redirect_to rooms_path
    if(@room.save)
         redirect_to rooms_path
    else  
      binding.pry 
      render action: 'new'
    end  
  end   


  def edit
    @room=Room.find(params[:id])
   binding.pry
  end

  def show
    @booking=Booking.new
    @room=Room.find(params[:id])
    @booking.room_id = @room.id
  end

  def update
     @room=Room.find(params[:id])
    if(@room.update_attributes(room_params))
        redirect_to room_path(@room.id)
        
        NotificationMailer.authorization_message_sending(@room).deliver!
    else
         render action: 'edit'
    end
  end
  def destroy
    @room=Room.find(params[:id])
    @room.destroy
    redirect_to rooms_path
  end  

private
def room_params
   params[:room].permit(:name,:description,:price,:rules,:address,:images,:latitude,:longitude,:city_id,:is_authorized,amenity_ids:[])   
end	  
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
   <% if(current_user.role_id == 2)%>
   <%@room.errors.full_messages.each do |msg|%>
   <%=msg%>
   <%end%>
   <%= form_for @room do |f|%>
   <label for="room_name">RoomName</label>
   <%=f.text_field :name%>
   <label for="room_description">Description</label>
   <%= f.text_field :description%>
   <label for="room_price">PRICE</label>
   <%= f.number_field :price %>
   <label for="room_rules">RULES</label>
   <%=f.text_field :rules%>
   <label for="room_address">ADDRESS</label>
   <%=f.text_field :address%>
   <label for="room_images">IMAGES</label>
   <%=f.file_field :images%>
   <label for="room_latitude">LATITUDE</label>
   <%=f.number_field :latitude%>
   <label for="room_city_id">CITYSELECT</label>
   <%= f.collection_select :city_id,City.all,:id,:name%>
   <label for="room_longitude">LONGITUDE</label>
   <%=f.number_field :longitude%>
  <label for="room_amenities">Amenitites</label>
   <%= f.collection_check_boxes :amenity_ids,Amenity.all,:id,:name do |name|%>
     <%=name.check_box%>
     <%=name.label%>
   <%end%>
   <%=f.submit "SubmitRoomDetails"%>
   <%end%>
   <%end%>
   <%if(current_user.role_id == 1)%> 
     <%@room.errors.full_messages.each do |msg|%>
         <%=msg%>
     <%end%>
   <%= form_for @room do |f|%>
   <%= f.radio_button :is_authorized,true%>authorize
   <%= f.radio_button :is_authorized,false%>unauthorize
   <%=f.submit "Authorize submit"%>
   <%end%>
   <%end%>

app/views/rooms/index.html.erb
     
     <%if(current_user.role_id != 1)%>
        <%@rooms.each do |room|%> 
             <%if(room.is_authorized == true)%>
                  <li><%=link_to room.name,room_path(room.id)%><br/></li>
             <%end%>
        <%end%>
     <%else%>   
        <%@rooms.each do |room|%>
             <ol>
             <%if(room.is_authorized == true)%>
                 <li><%= room.name%></li>
             <%end%>
             </ol>
        <%end%> 
      <%end%>      
<br/> <br/> <br/> <br/> <br/> <br/>




<ol>
<%@rooms.each do |room|%>
    <%binding.pry%>
    <%if(current_user.role_id == 1)%>
       	<%if((room.is_authorized == false)||(room.is_authorized == nil))%>
          <%binding.pry%>
          <%=room.name%>    
          <%=form_for room do |f|%>
          <%= f.radio_button :is_authorized,true%>authorize
          <%= f.radio_button :is_authorized,false%>unauthorize
          <%binding.pry%>
          <%= f.submit "authorization"%>
          <%end%><br/>
          <br/>
        <%end%>
       <%end%> 
<%end%>
</ol>

<br/> <br/> <br/> <br/> <br/> <br/>
<% if(current_user.role_id == 2)%>
MY Rooms(host)whose bookings needed to  be confirmed are here

      <%@rooms.each do |room|%>
      <%binding.pry%>
      <% if(room.is_authorized == true)%>
      <%if(room.user_id == current_user.id)%>
         <%Booking.all.where({room_id: room.id,is_confirmed: false} ).each do |booking|%>
               <%binding.pry%>            
               <li><%= link_to "confirm the  #{room.name} slot #{booking.start_date} and #{booking.end_date} #{booking.room.name}", edit_booking_path(booking.id)%><br/></li>
               <li><%= link_to "Delete the room booking",booking_path(booking.id), method: :delete,data: {confirm: "are u sure"} %></li>
               <%binding.pry%>
          <%end%>
        <%end%> 
        <%end%>
      <%end%>
 <%end%>
<ol>


<%if(user_signed_in? )%>
<%= link_to "add a new room",new_room_path %><br/>
<%end%>

<%= will_paginate @rooms %>

app/views/rooms/new.html.erb
  <% if @room.errors.any? %>
    <%@room.errors.full_messages.each do |msg|%>
       <br/>
       <%= msg%>
    <%end%>
  <% end%>


     <%= form_for @room do |f|%>
     <label for="room_name">RoomName</label>
     <%=f.text_field :name%>
     <label for="room_description">Description</label>
     <%= f.text_field :description%>
     <label for="room_price">PRICE</label>
     <%= f.number_field :price %>
     <label for="room_rules">RULES</label>
     <%=f.text_field :rules%>
     <label for="room_address">ADDRESS</label>
     <%=f.text_field :address%>
     <label for="room_city_id">CITYSELECT</label>
     <%= f.collection_select :city_id,City.all,:id,:name%>
     <label for="room_images">IMAGES</label>
     <%=f.file_field :images%>
     <label for="room_amenities">Amenitites</label>
     <%= f.collection_check_boxes :amenity_ids,Amenity.all,:id,:name do |name|%>
     <%=name.check_box%>
     <%=name.label%>
     <%end%>
     
     <%= f.submit "SubmitRoomDetails"%>
     <%end%>

  

app/views/rooms/show.html.erb
<%if(user_signed_in?)%>
  <%= @booking.errors.full_messages.each do |msg|%>
     <%=msg%><br/>
<%end%>
<%end%>


   <br/>
   NAME<%=@room.name%><br/>
   DESCRIPTION:<%=@room.description%><br/>
   PRICE:<%=@room.price%><br/>
   RuLES:<%=@room.rules%><br/>
   ADDRESS:<%=@room.address%><br/>
   IMAGES:<%=image_tag(@room.images,size: "100x100")%><br/>
   latitude:<%=@room.latitude%><br/>
   Longitude:<%=@room.longitude%><br/>
   CITY:<%=@room.city.name%><br/>
   USER:<%=@room.user.username%><br/>
   Authorization by admin:<%= @room.is_authorized %><br/> 
    <%@room.amenities.each do |amenity|%>
       <%=amenity.name%>----
       <%=amenity.description%><br/>
    <%end%>
<%if(user_signed_in?)||(@room.user_id==current_user.id)%>
   <%= link_to "DELETE THE ROOM", room_path(@room.id),method: :delete%><br/>
   <%= link_to "EDIT THE ROOM DETAILS",edit_room_path(@room.id)%><br/>
   <%= link_to "ADD A new AMENITY",new_amenity_path %>
<%end%> 
<%if(user_signed_in?)%>
  <%= @booking.errors.full_messages.each do |msg|%>
     <%=msg%><br/>
  <%end%>
  <iframe
    width="600"
    height="450"
    frameborder="0" style="border:0"
    src="https://www.google.com/maps/embed/v1/place?key=AIzaSyBr9ez4DKZFKkYmkLdO3ze_PGOKBxC2vAg&q=#{@room.address}" allowfullscreen>
   </iframe> 

  

  <%= form_for @booking do |f|%>
  <label for="booking_start_date">Start_date</label>
  <%= f.date_field :start_date %>
  <label for="booking_end_date">End_date</label>
  <%= f.date_field :end_date%>
  <label for="booking_price">booking_price</label>
  <%= f.hidden_field :price,value: @room.price%>
  <%= f.hidden_field :room_id,value: @room.id%>
  <%= f.submit "Book the room" %>
  <%end%>
  <%=link_to "Your previous bookings",  bookings_path%>      
<%end%> 
    